# -*- coding: utf-8 -*-
"""Esin_Ekiz_Midterm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lHeOE22gTP_LcBD-k_Y1N-xHvGZIa1dg

*Hello*, please change the file name as your name_surname_MIDTERM.ipynb and upload to the folder 'DROP MIDTERMS HERE' on Drive.
ex: atay_ilgun_MIDTERM.ipynb

Describe what ML is in 50 words.
"""

Machine Learning in briefly, it is primarily computer science and it was born as given classification or regression problem is solved by the machine. It is an algorithm category that enables software programs. You feed the data to the generic algorithm and it builds it's own logic.

"""Give 3 examples of ML in practical use in todays world - also, meditate on how it is being utilised as well."""

Google translate, spotify, siri.

"""In ML terminology what is an 'example', 'feature', 'label' and 'feature vector'?"""

An example is a particular instance of data. A feature is an input variable that "x" variable in linear regression. A label is that predicting the "y" variable.

"""In 100 words meditate on how future advancements on AI could affect your work practice as a communication designer."""

As machine learning develops, it may be recognizing designers reactions to machine recommendations and incorporating their unspoken preferences into the design process will accelerate productive design. Until recently, designers have used computers to solve logical problems involving the brain. But computers are beginning to enter the field of human creativity. Throughout history, people have shaped the world. People will go one step further and shape the objects that shaping the world.

"""Try to describe how you learn in algorithmic terms."""

By reading the formulas of data input and output use these datas on the computer.

"""Create a python dictionary for your name surname and year of birth."""

wow = {"name" : "esin", "surname" : "ekiz", "birthyear" : "1996"}

"""Write a conditional so If the first letter of your name is 'a' print 'my initial is a!'"""

if wow["name"] [0] == "a":
 print("my initial is a")

"""Write a conditional so If your surnames letter count is divisable by 3 print 'it is divisible' if not 'not divisible'."""

if len(wow["surname"]) % 3 == 0:
  print("it is not divisible")
else:
  print("it is not divisible")

"""Change your year of birth to 2678."""

wow["birthyear"] = 2678
print(wow)

"""Create a loop that goes through 20 to 40 and prints out the numbers that are divisble by 5."""

list_1 = range(20,40)
for everynumber in list_1:
   if everynumber % 5==0:
      print(everynumber)

"""Check the PDF on the Drive and calculate the neurons. Put all neurons and weights in python and do the calculation with them."""

print(0.87*0.06 + 0.12*0.12 + 0.62*0.47)

"""Using the code here:
https://github.com/anishathalye/neural-style
create a ***style transfer*** image.

Upload it along with this file.

You might need a file while doing this, it also is on the Drive!
"""